### ISSUE TITLE
Three-way diffing

### ISSUE THREAD

**Issue by niccolomineo** [L13/vscode-diff#101]
Hi, I would like to suggest adding a third panel where the user sees gathered the results of the actions taken on the "mine" and the "theirs" panels (in the same fashion as PyCharm).

**Comment by L13** [comment]
Hi, right now there are no plans for a 3 way diff, because the VS Code Diff Editor does not support it. It would be too confusing if you can diff 3 folders but you can not open the difference in an editor. I recommend to use multi compare and multi copy. If you open multiple diff panels with the same folder on the same side you can copy files from this folder across all diff panels at once.

**Comment by niccolomineo** [comment]
Hi, diffing three folders is not really what I mean. Take a look at how PyCharm uses the third panel.

**Comment by L13** [comment]
I have no PyCharm but if you mean the bottom pane like on this page https://www.jetbrains.com/help/pycharm/comparing-files-and-folders.html#comparing_folders you can open the VS Diff Editor for a preview to the side with `Alt + Double Click` or `Ctrl + Enter`. The keyboard shortcut works also with multiple files. Otherwise you have to send me a link with an example image or video what exactly you mean.

**Comment by niccolomineo** [comment]
This is what I mean: https://betterprogramming.pub/how-to-resolve-git-conflicts-faster-and-more-easily-in-your-favorite-ide-9d2984283a79

**Comment by L13** [comment]
The page is about Git conflicts, not folder comparisons. Neither my link nor your link shows a "third" pane for folder comparison. I do not provide any merge editor for files. I still use the VS Code Diff Editor. I recommend if PyCharm provides the features you need you should use this one.

**Comment by niccolomineo** [comment]
> The page is about Git conflicts, not folder comparisons. Neither my link nor your link shows a "third" pane for folder comparison. I do not provide any merge editor for files.

Sure, different purpose... but does that make the gist of the suggestion less pertinent / applicable? 🙂 Anyway, I understand implementing something like this may be a pain at this point of your extension's maturity. I hope Microsoft tackles this on its own, there's undoubtedly a lot of room for improvement there.

> I still use the VS Code Diff Editor.

Seeing native folder comparison and a 3-pane UI would be awesome. There's an ongoing hot discussion here: https://github.com/microsoft/vscode/issues/37350

> I recommend if PyCharm provides the features you need you should use this one.
I am never going back to using PyCharm as long as that's the UI it's going with. It is, quite frankly, a mess! 😄
