### ISSUE TITLE
Option to use `git --work-tree=folder diff`

### ISSUE THREAD

**Issue by munael** [L13/vscode-diff#102]
`git --work-tree=/path/to/another_repo diff` allows git to do the diffing with multiple repositories, which handles, for example, file moves.

Would be great to have a way to request that method and have the output rendered as usual as a list of files.

**Comment by L13** [comment]
Hi, the extension still allows to compare any two folders on the disk. If you want to compare two different repositories you can just select them by dialog or paste the paths into the input fields.

**Comment by munael** [comment]
@L13 - Hi o/ Yes, that's true. But, at least as I've tried it, the extension doesn't recognize file moves or renames?

**Comment by L13** [comment]
Yes, the extension does not check if a file was renamed or moved. If you want to compare files with different names or paths you can drag'n drop the paths in the list view. Just drag the path of a file to another file path and a diff editor opens with these two files. This works also with folders and symlinks.

Adding a detection for moved or renamed files as a builtin feature I have to think about first. Even git has its limitation because it depends on the branch history which I do not have and does not exist in non git projects. To figure out if a file has been moved or renamed will end up in a guessing game or in a hugh performance heap. I do not check the code inside a file. The extension compares just raw byte data. So detecting a rename with small changes in a file like git does will be really difficult. These affects also changes in leading and trailing whitespace or line endings.

**Comment by L13** [comment]
Hi, after thinking about it I decided this feature is out of scope. Not every folder has a git history and anything else would be guessing.
