### ISSUE TITLE
Access, export, modify favorites as a config file?

### ISSUE THREAD

**Issue by ripe909** [L13/vscode-diff#112]
Is it possible to access the settings for the Favorites directly and edit them?  

Also, this would make it possible to export them from one machine and load them into another?

**Comment by L13** [comment]
Hi, right now it is not possible to export the favorites as a user. The feature exists only in the developer mode and is not ready or final for public use. I use it just for testing.

The development of the extension has been paused until autumn, because I have no time to do something. I put it on my todo list.

**Comment by L13** [comment]
Hi, the feature is now available.
