### ISSUE TITLE
Error Copying Selection from one side to another

### ISSUE THREAD

**Issue by estebanavv** [L13/vscode-diff#140]
Error: "Cannot convert a Symbol value to a string"

When selecting a file on one side and using the icon to copy or the icon on top to copy selection it always fails with the same errors.
![Screen Shot 2023-10-04 at 11 54 32 AM](https://github.com/L13/vscode-diff/assets/9424792/c94db47a-32bf-4439-872a-3e2d5ecd6253)

**Comment by L13** [comment]
Hi, after some research I'm really confused, because this error cannot or should not happen. I know what this error means, but at this part of the code I don't use Symbols. I have released a new version on the VS Code Marketplace which shows the stack trace in the error message. Please download the new version 1.3.3 and repeat the action which causes the error and post the complete message. Thank you in advance.

**Comment by estebanavv** [comment]
Thank you. Now it works sometimes and other times it gets stuck without error. Notice the blue bar on top stays indefinitely and I have to quit the VS.
Attached video. 
https://github.com/L13/vscode-diff/assets/9424792/aa466fa6-6569-4972-b4a7-1ad742478933

**Comment by L13** [comment]
I have released version 1.3.4 which fixes an error if more than one panel is open and if one of them is closed an error appears. But in all my tests this doesn't affect any feature. I don't think that this fixes the issue because it seems the webview message api is broken. I found a ticket in the vscode repo which is three weeks old and they made some changes.
