### ISSUE TITLE
Support for File System APIs

### ISSUE THREAD

**Issue by gbrueckl** [L13/vscode-diff#158]
Are there any plans to also support custom [VSCode FileSystemProvider](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider)
i am currently working on two VSCode extensions which heavily rely on them and it would be great to compare different files and folders from my custom file system.

its basically about exchanging all references to `fs` with `vscode.fs` and slight modifications if some functions are different/not there

regards,
-gerhard

**Comment by L13** [comment]
Hi, long time ago I started a prototype and after a couple of hours I figured out it is not as easy as it seems. It got more and more complicated because nodejs supports features which do not exist in the vscode.fs api. After that test I have rewritten my other extension called Projects which supports the vscode api now. But this was way more than just a couple of lines. Only exchanging the api doesn't work and it is way more than just this.

The extension is a spare time project. In the near future where are no plans to do that because I have to focus on other stuff.

**Comment by gbrueckl** [comment]
thanks for your quick reply
its fully understandable, I know how timeconsuming it can be to maintain an extension
i was fortunate enough to start directly with the `vscode.workspace.fs` for all my file operations so I did not have a later migration. Though the main reason for me was the support in https://vscode.dev
