### ISSUE TITLE
Advice on how to add synonyms

### ISSUE THREAD

**Issue by CarlosKlappTheOFE** [L13/vscode-diff#19]
I'd like your advice on how to implement a new feature for adding equivalents or synonyms to the diff. The purpose is to consider equivalents as being the same.

For example, consider single quote (') and double quote (") as being equivalent. When enabled these lines would be considered equivalent.
    const cr = require('crypto');               const cr = require("crypto");

Or when a variable has been renamed: cr is equivalent to crypto
     const cr = require('crypto');               const crypto = require('crypto');

Your advice is greatly appreciated.

**Comment by L13** [comment]
Hi, I had a similar idea about comparing angular components, but the more I thought about it, the more it got complicated. Finally I made the decision not to do it, because in my opinion it goes far beyond what a diff tool should do. The idea of this extension was always to add just a folder comparison to the basic diff features of VS Code.

I think you can handle things like that with ESLint and TSLint or you minify your source and compare the results.
