### ISSUE TITLE
Ignore specific files

### ISSUE THREAD

**Issue by adamreisnz** [L13/vscode-diff#21]
Hi there, first of all thanks for making this extension, it's really great and has saved me a lot of time.

Our use case is to maintain two slightly different versions of the same app, which do require a separate repository, with a few differences, but mainly a large shared code base.

We use L13 to port over any changes that have been made in V2 to V1. 

For the most part, this works great, however what would save us even more time, is if we could specify which files to ignore for a certain comparison.

That way, we could mark all the files that we know are different to be ignored, so we would only see the changes that we're interested in, which will allow us to process them a lot faster.

I was thinking perhaps you could utilise a configuration file in the project root (e.g. folder that is being compared), and specify in there which files you want ignored. Kind of like a `.gitignore` but for L13 specifically.

The tricky bit is that ideally it would also allow you to specify files that don't exist in the folder, so that when comparing and they show up as new, it won't show them either.

What are your thoughts?

**Comment by adamreisnz** [comment]
It appears this is already supported in the form of `l13Diff.ignore`! I will have a play with it and see how that goes.

**Comment by adamreisnz** [comment]
Actually this works globally, not per project, so I think my request is still a valid one

**Comment by L13** [comment]
Hi, I put it on my feature list. In the mean time you can use the search widget (Cmd + F / Ctrl + F) and the following regex:

^(?!path/to/ignore|another/path/to/ignore).*$

About the implementation. I try to avoid local files, because in my opinion we have still too many files in the root folder in some projects.

I think I will create a separated input field like in the search view of VS Code (files to exclude) and save the pattern in a favorite diff, too. Makes it easier if you compare two folders next time.

Finally this is a spare time project, so I make no promises when I will do it.

**Comment by adamreisnz** [comment]
Thanks, a regex will not be very practical as we have quite a few paths in one of the projects, but I will see if it helps.

If we could save it for a favourite that would work I suppose.

**Comment by L13** [comment]
Hi, I need your help. In the past days I was thinking about this feature and the more I thought about it the more I came up with a different solution which still exists. Am I right that you want to save a list of files you want to ignore for a comparison which will be saved inside a project? This feature still exists in VS Code. There are two solutions.

First you can save the "l13Diff.ignore" list in the ".vscode/settings.json" in each project. If you open the project this setting will be used instead of the global one. But the project has to be the current workspace. Otherwise it doesn't work.

```json
{
    "l13Diff.ignore": [
        "files",
        "to",
        "ignore"
    ]
}
```

The second solution is to create a ".code-workspace" file and there you can use

```json
{
    "settings": {
        "l13Diff.ignore": [
            "files",
            "to",
            "ignore"
        ]
    }
}
```

Does this help?

The only thing which is not working right now is that both folders are not a workspace or one of them is not the current workspace. This is something that I have to implement.

**Comment by adamreisnz** [comment]
Yes, the problem is that I am currently not using workspaces because I am using a project manager plugin in VSCode and when it opens a folder, it doesn't automatically open the corresponding workspace. This is a known issue, and hopefully it will be resolved some day, but because it was getting so annoying to see that message I resorted to use non-workspace projects.

The solution will probably work if I do use workspaces, so that would be a good way of tackling this. I guess as you point out the only drawback would be that if you do the comparison from another window which is not the workspace, it will not work.

Not a big priority though, so if you want to leave this on the back burner for later that's fine. Otherwise feel free to close it and I'll try to use the work space solution instead.

**Comment by L13** [comment]
If the plugin is called "Project Manager" when I know what you mean. That was one reason why I have created [L13 Projects](https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-projects). This extension supports L13 Diff. It also supports workspace files. Do you wanna try it?

**Comment by adamreisnz** [comment]
Yeah sure I might, I'll have a look shortly, thanks!

**Comment by L13** [comment]
Hi, the feature is implemented and the extension supports '.vscode/settings.json' now, even if the folder for the comparison is not the current workspace folder. If the folder is a subfolder of a workspace folder the settings file will be automatically detected and used for the comparison, too.
