### ISSUE TITLE
folders selection

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-diff#27]
first, thank you for sharing this, the extension is essential .

it would be good to add the both folders selection buttons to the Explorer context menu, its seem to be fine in terms of space, and it would be meaningful because the folders for comparison are usually located nearby . maybe it can be made settable/optional .

also, after i selected the first of (3251) differing files, the VSC made the whole system lag with bunch of this:
![Screenshot 01-26-2020 15 57 36](https://user-images.githubusercontent.com/13949704/73135665-b0c01e80-4055-11ea-8b6f-9a5505a80024.png)
; (not sure if its because of the extension)

**Comment by L13** [comment]
Hi and thank you.

If I unterstand your request correctly you want to use or select files or folders for the comparison from the VS Code Explorer? This is possible right now. Just select one or two files/folders and open the context menu and then select "Open with L13 Diff". Or you can drag'n drop the file/folder into the input fields of the extension. This works also with the native Finder/Explorer.

I have never seen the second issue and can't reproduce it. This seems to be an VS Code error because I'm using their API to open a diff. My extension just compares folders.

**Comment by irvnriir** [comment]
@L13 .
since i use the Explorer practically only to select file/-s per 1 editor window, i didn't even try to multi-select them, thanks .
