### ISSUE TITLE
Multiple diffs open simultaneously

### ISSUE THREAD

**Issue by jastich** [L13/vscode-diff#48]
Hello,

Thank you for a quality extension.  Very useful!

I observed that I can only diff a single pair of folders at any time.  Could the extension be enhanced to support multiple diffs simultaneously?

Thank you!

**Comment by L13** [comment]
Hi, thank you. The extension supports multiple panels since version 0.25.0. You can open a new panel by pressing Cmd/Ctrl + L Cmd/Ctrl + L again or by click on the first icon in the favorites view. I also recommend to read the description for multi compare and multi copy ```Copy files to the left/right folder```, which supports copying the same files across multiple panels at once. It is also possible to group multiple favorites and open them all at once.
