### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mozgbrasil** [L13/vscode-diff#49]
Hello good afternoon

If you can help me

See it's being applied

    Maximum call stack size exceeded

How should I proceed?

![Captura de tela de 2020-09-03 14-50-40](https://user-images.githubusercontent.com/17202780/92150011-2c0c5e80-edf5-11ea-922c-e5f65fc15f32.png)

**Comment by L13** [comment]
Hi, interesting. I have never seen this before. Have you tried to exclude files which you don't need for the comparison with ```l13Diff.ignore```?

**Comment by mozgbrasil** [comment]
Yes

    "l13Diff.ignore": [
      "dist",
      ".DS_Store",
      ".git",
      ".hg",
      ".svn",
      "CVS",
      "node_modules"
    ]

**Comment by L13** [comment]
Hi, this is strange. I have made right now a super weird comparison with a huge amount of files, but everything was fine. Does this also happen if you just compare a subfolder or can you figure out if it is a specific folder inside the comparison? Or does this happen only with this comparison? Thanks in advance.

**Comment by L13** [comment]
Hi, I have another idea. Can you open the log (Cmd/Ctrl+L Cmd/Ctrl+O) and tell me when it crashes? Because in the log you can see if it happens during scanning the folders or while all files will be compared. Thanks in advance.

**Comment by theprinze** [comment]
Was this resolved?  I am having the same issue.  I checked the log and it scanned both folders the firsts found 869 entries and the 2nd found 848 entries but the the stopped and the "maximum call stack exeeded error" popped up.  Any clue how to fix this?

Thanks.

**Comment by theprinze** [comment]
Okay so I checked the window log and there were a bunch of errors with some other extensions.  I disabled the extensions and it still was not working.  But then suddenly after I kept hitting compare it work despite the fact that the error still popped up. It did show a warning message i the window log:

[renderer1] [warning] UNRESPONSIVE extension host, 'L13RARY.l13-diff' took 79% of 946.48ms, saved PROFILE here: 'C:\Users\plu2o\AppData\Local\Temp\exthost-6d020b.cpuprofile' [{"id":"gc","total":20510,"percentage":2},{"id":"L13RARY.l13-diff","total":744745,"percentage":79},{"id":"program","total":168645,"percentage":18},{"id":"self","total":8189,"percentage":1}]

**Comment by L13** [comment]
> I am having the same issue. I checked the log and it scanned both folders the firsts found 869 entries and the 2nd found 848 entries but the the stopped and the "maximum call stack exeeded error" popped up. Any clue how to fix this?

Hi, thank you very much. This helps a lot. It seems the compare process is blocking if too many comparisons are done. The process is right now synchronous. I will rewrite the process to async. This takes some time.

**Comment by L13** [comment]
I found the reason by accident, but the error message, which is provied by nodejs, is wrong. Because if this error appears it means a function is called synchronous and recursive thousands of times, which is not the case in the compare process. If the property "l13Diff.ignoreTrimWhitespace" is "on" or "default" and "diffEditor.ignoreTrimWhitespace" is checked the error appears with text files which have ultra long lines like minified javascript files. The error is caused by the following line ```push.apply(newBuffer, cache.slice(j, k))```. So javascript does some weird stuff under the hood if you call this line. I will provide a fix tomorrow.

The high cpu performance is also a result of this kind of comparison. If the property "l13Diff.ignoreTrimWhitespace" is "on" or "default" and "diffEditor.ignoreTrimWhitespace" is checked or "l13Diff.ignoreEndOfLine" is checked I have to rewrite the buffers. So if more and more text files are different and have to be compared, the higher the cpu load is. I have implemented a lot of checks to do only the stuff which is necessary. I recommend to disable the properties if they are not required for a comparison if you have to compare many different text files.
