### ISSUE TITLE
Question: How is "Show all modified files" determined?

### ISSUE THREAD

**Issue by KThen** [L13/vscode-diff#58]
**Statement**
I am trying to compare two similar folders but are in different repositories. When I have "Show all modified files" selected, it shows me files which the content inside are the same.

**Expected Output**
It should only show if there are differences in the content of the two files, and should ignore the modified date of the file.

**Current Output**
It shows the files that the contents are the same.

**Comment by L13** [comment]
Hi, it seems the property "l13Diff.ignoreEndOfLine" is false (default value, not checked). Visual Studio Code ignores line endings in a diff view. CRLF and LF is the same for VS Code, but you can't see it. You have to install an extension to make it visible. If my extension shows a file as modified it is definitely modified, because the comparison is always by contents.

**Comment by KThen** [comment]
Thanks for the quick response. After I set the l13Diff.ignoreEndOfLine to true it works like a charm. Closing this issue.
