### ISSUE TITLE
Select files and folders in local volume when in container

### ISSUE THREAD

**Issue by niccolomineo** [L13/vscode-diff#66]
Hi, is it possible to be able to select the local volume when running project in a container?

Right now, I seem to be able to only browse files and folders within the container.

**Comment by L13** [comment]
Hi, comparing remote files with local files are not possible right now because the vscode api does not provide the full feature set which nodejs does and the extension use them. Even if it would be it means way more trouble than it seems in the first place. I started with a prototype to switch to the vscode api, but I came up that it doesn't work. So there are no plans to do this.
