### ISSUE TITLE
Feature request: ignore creation and modification date in difff

### ISSUE THREAD

**Issue by filvi** [L13/vscode-diff#69]
Hi I would like to know if is possibile to perform a line by line check if the file has been  actually modified, I have two version and the creation date for some reason seems to be different, so the plugin shows me all the files and not the actual changes, the files are exactly the same. 
I think it should be great to have a setting in which you can toggle (check line by line / by modified date).

Thanks for making this  plugin BTW!

**Comment by L13** [comment]
Hi, it seems the property "l13Diff.ignoreEndOfLine" is false (default value, not checked). Visual Studio Code ignores line endings in a diff view. CRLF and LF is the same for VS Code, but you can't see it. You have to install an extension to make it visible. If the extension shows a file as modified it is definitely modified, because the comparison is always by contents.

**Comment by filvi** [comment]
Ah thank you for your answer, and for letting me know that, Kudos to you :)

Filippo Vicari

Il lun 11 gen 2021, 17:54 L13|RARY <notifications@github.com> ha scritto:

**Comment by filvi** [comment]
Setting the "l13Diff.ignoreEndOfLine" to False fixes the problem I encountered
