### ISSUE TITLE
Incorrect paths in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by jezpipkin** [L13/vscode-diff#98]
This has been working fine until updating VS Code last week.

In Windows I have 
C:\git\test\aa and C:\git\test\bb

I open `C:\git\test `in VSCode in Windows, select `aa `and compare `bb` with no problem

I open `/mnt/c/git/test` in VSCode in WSL, select `aa` and compare `bb`, error 'The left path "\mnt\c\git\test\aa" does not exist.'

`\` looks the wrong way round, but if I change the paths to `/mnt/c/git/test/aa` etc, the error persists.

If I browse for the folders in Diff Folders, the path shows as `/mnt/c/git/test/`, I select `aa`, the path shows as `/mnt/c/git/test/aa`, click ok, and it has switched to `\mnt\c\git\test\aa` , and the error persists.

If I edit the paths to Windows paths, effectively change `\mnt\c\` to `c:\`, it works, so it's usable still but some of the convenience has gone.

(it's also working ok in Linux, just this odd thing with WSL)

And thanks for making this available, I use it daily, it's very much appreciated.

**Comment by L13** [comment]
Hi, and thank you.

I also updated the extension last week, because VS Code released a new feature called Workspace Trust, otherwise my extension would not work properly anymore. With this release I also changed one other thing  called `extensionKind`. The extension does not officially support remote development right now. But I thought it does not have any impact, because in my tests with a docker container, everything worked like expected. But it seems that VS Code Insider did not use the correct package definition in the development environment.

You can override this value. Please open the settings as JSON and add the following lines:

```json
"remote.extensionKind": {
	"L13RARY.l13-diff": [
		"workspace",
		"ui"
	]
}
```

Please tell me if the previous behavior is back with this fix. If this is true I have to release a bug fix. Thank you in advance.

**Comment by jezpipkin** [comment]
Hi, that works.  It's back to working as before, many thanks

**Comment by L13** [comment]
Hi, I updated the extension. The new version 1.0.3 includes the same order for `extensionKind` like in the lines above. So you can remove the fix in the settings.
